const productsDB = [
  {
    id: 1,
    name: "Tyre Valve",
    price: 13,
    img: "./src/images/valve.jpg",
    desc: "Durable valves",
    related: [4,8,11],
    use: "Allows air to enter and stay in the tyre.",
    instructions: [
      "Remove the old valve if replacing.",
      "Insert the new valve stem into the rim hole.",
      "Ensure it sits tight and seal properly.",
      "Inflate the tyre to the recommended pressure.",
      "Check for leaks by applying soapy water around the valve—bubbles indicate a leak.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 2,
    name: "Tyre Repair Plug",
    price: 200,
    img: "./src/images/tyre-plug.jpg",
    desc: "Strong cushion gum",
    related: [6,5],
    use: "Quick repair for tubeless tyre punctures.",
    instructions: [
      "Locate puncture.",
      "Use reamer tool to clean/enlarge hole.",
      "Thread plug into insertion tool.",
      "Push plug into hole and pull tool out, leaving plug in tyre.",
      "Trim excess plug and inflate tyre.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 3,
    name: "Cushion Gum",
    price: 13,
    img: "./src/images/cushion-gum.jpg",
    desc: "Durable valves",
    related: [9],
    use: "Place between the tyre and rim to reduce vibration or improve ride comfort.",
    instructions: [
      "Clean the rim surface.",
      "Cut the cushion gum to size if needed",
      "Fit it between the tyre bead and rim evenly.",
      "Inflate the tyre to seat the bead properly.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 4,
    name: "Key Valve",
    price: 200,
    img: "./src/images/key-valve.jpg",
    desc: "durable key valves",
    related: [1,11],
    use: "For tightening, removing, or adjusting valves.",
    instructions: [
      "Attach the key valve tool to the valve core.",
      "Turn counterclockwise to remove or clockwise to tighten.",
      "Don’t overtighten—just snug enough to prevent leaks.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 5,
    name: "Tire Patches",
    price: 13,
    img: "./src/images/tyre-patch.jpg",
    desc: "Durable valves",
    related: [6,2],
    use: "Repairs punctures in inner tubes or tubeless tyres.",
    instructions: [
      "Locate puncture and mark it.",
      "Roughen area around puncture with sandpaper or reamer.",
      "Apply vulcanizing cement and let it become tacky.",
      "Apply patch firmly, press out air bubbles",
      "Let it set as instructed, then inflate tyre slowly.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 6,
    name: "Vulcanizing Cement / Rubber Glue",
    price: 200,
    img: "./src/images/rubber-glue.jpg",
    desc: "Strong gum",
    related: [2,5],
    use: "Bonds tyre patches or plugs to rubber.",
    instructions: [
      "Clean and roughen the repair area.",
      "Apply cement evenly.",
      "Wait 2–5 minutes for it to become tacky.",
      "Apply patch or plug and press firmly.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 7,
    name: "Tyer Pressure Gauge",
    price: 13,
    img: "./src/images/pressure-gauge.jpg",
    desc: "Durable valves",
    related: [],
    use: "Measures air pressure in tyres.",
    instructions: [
      "Remove valve cap.",
      "Press gauge onto valve stem.",
      "Read pressure; compare with tyre’s recommended PSI.",
      "Adjust air pressure if necessary.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 8,
    name: "Air Compressors / Inflators",
    price: 200,
    img: "./src/images/air-compressor.jpg",
    desc: "Strong gum",
    related: [],
    use: "fills tyers with air.",
    instructions: [
      "Connect hose to tyre valve.",
      "Turn on compressor and monitor pressure gauge.",
      "Stop inflating once tyre reaches recommended PSI.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 9,
    name: "Bead Sealer",
    price: 13,
    img: "./src/images/bead-sealer.png",
    desc: "Durable valves",
    related: [3],
    use: "Seals tyre bead to rim to prevent leaks.",
    instructions: [
      "Clean rim and tyre bead.",
      "Apply a thin layer of bead sealer around the rim edge.",
      "Mount tyre and inflate slowly.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 10,
    name: "Balancing Weights",
    price: 200,
    img: "./src/images/balancing-weights.jpg",
    desc: "Strong gum",
    related: [],
    use: "Ensures wheels spin smoothly without vibration.",
    instructions: [
      "Place tyre on balancing machine.",
      "Machine indicates where weights are needed.",
      "Clip or stick weights to rim as directed.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
  {
    id: 11,
    name: "Tyer Inflator Adaptors",
    price: 200,
    img: "./src/images/inflator-adaptor.jpg",
    desc: "Strong gum",
    related: [1,4],
    use: "Connects different valve types to pump.",
    instructions: [
      "Attach adapter to pump nozzle.",
      "Connect to valve type (Presta, Schrader, etc.).",
      "Inflate tyre and remove adapter.",
    ],
    manufacturer: "A",
    manufacturerUrl: "a",
  },
];

export default productsDB